### PR TITLE
Added support of postcss-cli parameterless options. Fixed running transformer on Windows OS

### PR DESCRIPTION
**Pull request by Ne4istb**
For me it is required as i want to use postcss plugins without installing them globally.

### CODE REVIEW

**Comment by ajlai** [comment]
Thanks for adding this! I'll take a closer look at this tonight.

**Comment by ajlai** [comment]
I think we can already add parameterless arguments without needing a special options key.
Example:

``` yaml
arguments:
- use: autoprefixer
- autoprefixer.browsers: Firefox 38, Safari 9
- local-plugins: ""
```

Does that work for your use case?

**Comment by Ne4istb** [comment]
@ajlai Thanks, it works for me. I missed this possibility))
Regarding Windows issues: i have some more problems and still investigating them. I'l close this PR and will create new issue/PR when will have some more details.

**Comment by ajlai** [comment]
@Ne4istb I think it's still worthwhile updating the documentation for options such as `--local-plugins` so others with the same use case won't run into the same issue. Let me know if you want to update the README; if not I can do that.

Thanks for looking into the Windows issues too! I don't have a windows machine so I can't test that workflow.

**Comment by Ne4istb** [comment]
@ajlai Good idea. I'll do it a bit later.

**Pull request closed without merging**
